### ISSUE TITLE
The Armor & Health Value will sometimes display improperly.

### ISSUE THREAD

**Issue by Kfcdragon756** [mbien1981/_hud#4]
![20241216111640_1](https://github.com/user-attachments/assets/7c8ee689-08ee-4d6f-a3d6-d3f36916872c)
As the picture shows, the AP Value didn't display properly (The number "0" is cut half?), and sometimes this also happens on HP value.

**Comment by mbien1981** [comment]
Should be fixed as of 31d4be9
